apiVersion: v1
kind: Namespace
metadata:
  name: machine
---
apiVersion: sla-operator.dcn.com/v1alpha1
kind: Slaml
metadata:
  name: slaml-sample
  namespace: machine
spec:
  IsSla: "true"
  slaTarget: 50
  name: pytorch-job
  tasks: [
      {
        taskName: "master",
        containerImage: "model_training",
        containerRegistry: "ddocker122",
        containerTag: "latest",
        containerReplicas: 1,
        cpu: "2m",
        memory: "3Mi"
      },
      {
        taskName: "worker",
        containerImage: "model_training",
        containerRegistry: "ddocker122",
        containerTag: "latest",
        containerReplicas: 5,
        cpu: "2m",
        memory: "2Mi"
      }
      
    ]
