---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sla-operator.dcn.com
  resources:
  - slamls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sla-operator.dcn.com
  resources:
  - slamls/finalizers
  verbs:
  - update
- apiGroups:
  - sla-operator.dcn.com
  resources:
  - slamls/status
  verbs:
  - get
  - patch
  - update
